version: "3.7"

services:

#  mycodo_influxdb:
#    container_name: mycodo_influxdb
#    build:
#      context: ./
#      dockerfile: docker/influxdb/Dockerfile
#    env_file:
#      - 'docker/influxdb/env.influxdb'
#    volumes:
#      - mycodo_influxdb:/var/lib/influxdb
#    ports:
#      - 8086:8086

#  mycodoinfluxdb:
#    ports:
#      - 8086:8086
#    volumes:
#      - mycodo_influxdb:/var/lib/influxdb2
#    image: influxdb:latest
#    environment:
#      - DOCKER_INFLUXDB_INIT_MODE=setup
#      - DOCKER_INFLUXDB_INIT_USERNAME=mycodo
#      - DOCKER_INFLUXDB_INIT_PASSWORD=mmdu77sj3nIoiajjs
#      - DOCKER_INFLUXDB_INIT_ORG=mycodo
#      - DOCKER_INFLUXDB_INIT_BUCKET=mycodo_db

  mycodonginx:
    labels:
      - kompose.service.group=sidecar
    container_name: mycodo_nginx
    restart: always
    image: nargetdev/mycodonginx:c0.0.0-v8.15.1
#    build:
#      context: ./
#      dockerfile: docker/nginx/Dockerfile
    volumes:
      - mycodo:/usr/local/mycodo
      - mycodo_log:/var/log/mycodo
      - mycodo_ssl_certs:/home/mycodo/mycodo/mycodo_flask/ssl_certs
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mycodoflask

  mycododaemon:
    labels:
      - kompose.service.group=sidecar
    container_name: mycodo_daemon
    image: nargetdev/mycodoapp:8.15.1
#    image: nargetdev/mycodoflask:c0.0.0-v8.15.1
    restart: always
    environment:
      - TZ=America/New_York  # See https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for valid time zones
    volumes:
      - mycodo:/usr/local/mycodo
      - mycodo_env:/home/mycodo/env
      - mycodo_databases:/home/mycodo/databases
      - mycodo_cameras:/home/mycodo/cameras
      - mycodo_custom_functions:/home/mycodo/mycodo/functions/custom_functions
      - mycodo_custom_actions:/home/mycodo/mycodo/actions/custom_actions
      - mycodo_custom_inputs:/home/mycodo/mycodo/inputs/custom_inputs
      - mycodo_custom_outputs:/home/mycodo/mycodo/outputs/custom_outputs
      - mycodo_custom_widgets:/home/mycodo/mycodo/widgets/custom_widgets
      - mycodo_custom_user_scripts:/home/mycodo/mycodo/user_scripts
      - mycodo_log:/var/log/mycodo
      - mycodo_ssl_certs:/home/mycodo/mycodo/mycodo_flask/ssl_certs
      - /dev:/dev
      - /sys:/sys
      - ./bindmount/opt:/opt
    privileged: true
    command: bash -c "wget --quiet --no-check-certificate -p http://mycodonginx/ -O /dev/null && 
                      PYTHONPATH=/home/mycodo /home/mycodo/env/bin/python mycodo_daemon.py"
    depends_on:
      - mycodoflask

  mycodoflask:
    labels:
      - kompose.service.group=sidecar
    container_name: mycodo_flask
    image: nargetdev/mycodoapp:8.15.1
#    image: nargetdev/mycodoflask:c0.0.0-v8.15.1
    hostname: mycodohost  # Change to your desired hostname
#    build:
#      context: ./
#      dockerfile: docker/Dockerfile
    restart: always
    environment:
      - TZ=America/New_York  # See https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for valid time zones
    volumes:
      - mycodo:/usr/local/mycodo
      - mycodo_env:/home/mycodo/env
      - mycodo_databases:/home/mycodo/databases
      - mycodo_cameras:/home/mycodo/cameras
      - mycodo_custom_functions:/home/mycodo/mycodo/functions/custom_functions
      - mycodo_custom_actions:/home/mycodo/mycodo/actions/custom_actions
      - mycodo_custom_inputs:/home/mycodo/mycodo/inputs/custom_inputs
      - mycodo_custom_outputs:/home/mycodo/mycodo/outputs/custom_outputs
      - mycodo_custom_widgets:/home/mycodo/mycodo/widgets/custom_widgets
      - mycodo_custom_user_scripts:/home/mycodo/mycodo/user_scripts
      - mycodo_custom_user_css:/home/mycodo/mycodo/mycodo_flask/static/css/user_css
      - mycodo_custom_user_js:/home/mycodo/mycodo/mycodo_flask/static/js/user_js
      - mycodo_log:/var/log/mycodo
      - mycodo_ssl_certs:/home/mycodo/mycodo/mycodo_flask/ssl_certs
      - mycodo_influxdb:/var/lib/influxdb
      - /dev:/dev
      - /var/run/docker.sock:/var/run/docker.sock:ro  # Permits container to restart itself
    privileged: true
    command: /home/mycodo/env/bin/python -m gunicorn --workers 1 --bind unix:/usr/local/mycodo/mycodoflask.sock start_flask_ui:app
#    depends_on:
#      - mycodoinfluxdb

# Uncomment the following blocks and rebuild to enable Grafana and/or Telegraf

#  mycodo_telegraf:
#    image: telegraf:latest
#    container_name: mycodo_telegraf
#    volumes:
#      - ./docker/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
#    depends_on:
#      - mycodo_influxdb

#  mycodo_grafana:
#    image: grafana/grafana:latest
#    container_name: mycodo_grafana
#    env_file:
#      - './docker/grafana/env.grafana'
#    volumes:
#      - mycodo_grafana:/var/lib/grafana
#    ports:
#      - 3000:3000
#    depends_on:
#      - mycodo_influxdb

volumes:
  mycodo:
  mycodo_env:
  mycodo_cameras:
  mycodo_custom_functions:
  mycodo_custom_actions:
  mycodo_custom_inputs:
  mycodo_custom_outputs:
  mycodo_custom_widgets:
  mycodo_custom_user_scripts:
  mycodo_custom_user_css:
  mycodo_custom_user_js:
  mycodo_databases:
  mycodo_ssl_certs:
  mycodo_log:
  mycodo_influxdb:
  mycodo_grafana:
