site_name: Mycodo
site_url: https://kizniche.github.io/Mycodo
site_author: Kyle T. Gabriel
site_description: Documentation for Mycodo
repo_name: 'kizniche/Mycodo'
repo_url: 'https://github.com/kizniche/Mycodo'
extra:
    version: 8.12.9

plugins:
  - search:
      lang:
        - en
  - minify:
      minify_html: true
  - with-pdf:
      custom_template_path: docs/custom_pdf
      cover_title: Mycodo
      cover_subtitle: Environmental monitoring and regulation system
      cover_logo: images/logo.png
      copyright: Copyright Â© 2021
      output_path: ../docs/mycodo-manual.pdf

theme:
  name: material
  language: 'en'
  logo: images/favicon.png
  favicon: images/favicon.png
  features:
    - navigation.tabs
    - navigation.top
  palette:
    - scheme: preference
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Barlow
    code: Roboto Mono

markdown_extensions:
  - admonition
  - toc:
     permalink: "~"
     toc_depth: 4
  - pymdownx.mark
  - pymdownx.tabbed
  - pymdownx.emoji:
  - pymdownx.betterem
  - pymdownx.caret
  - codehilite
  - meta

nav:
  - Home: index.md
  - About.md
  - Frequently Asked Questions: Frequently-Asked-Questions.md
  - Usage:
    - Data Viewing: Data-Viewing.md
    - Inputs.md
    - Maths.md
    - Outputs.md
    - Functions.md
    - Calibration.md
    - Methods.md
    - LCDs.md
    - Alerts.md
    - Notes.md
    - Camera.md
    - Energy Usage: Energy-Usage.md
  - Supported Devices:
    - Inputs Sorted by Measurement: Supported-Inputs-By-Measurement.md
    - Supported Inputs: Supported-Inputs.md
    - Supported Outputs: Supported-Outputs.md
    - Supported Functions: Supported-Functions.md
    - Supported Widgets: Supported-Widgets.md
    - I2C Multiplexers: I2C-Multiplexers.md
    - Analog-To-Digital Converters: Analog-To-Digital-Converters.md
    - Interfaces.md
    - Dependencies.md
    - Device Notes: Device-Notes.md
  - System:
    - System Information: System-Information.md
    - System Configuration: Configuration-Settings.md
    - Upgrade/Backup/Restore: Upgrade-Backup-Restore.md
    - Export/Import: Export-Import.md
    - Mycodo Client: Mycodo-Client.md
    - API.md
  - Troubleshooting.md
  - Translations.md
